// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASgWTcAHvywXNu0njR0QutsiQJDBpHEB8',
    appId: '1:127365705665:web:c320169613bc45e5440940',
    messagingSenderId: '127365705665',
    projectId: 'trippy-862df',
    authDomain: 'trippy-862df.firebaseapp.com',
    storageBucket: 'trippy-862df.firebasestorage.app',
    measurementId: 'G-WS6084733G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-k8vRdvDV397CRObgPv9_X5GfH7rReIg',
    appId: '1:127365705665:android:2473003ddde1b0f5440940',
    messagingSenderId: '127365705665',
    projectId: 'trippy-862df',
    storageBucket: 'trippy-862df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjW0orJbltG_RpqEkZPA3jl_pw9ONQhYw',
    appId: '1:127365705665:ios:170f882a00b289da440940',
    messagingSenderId: '127365705665',
    projectId: 'trippy-862df',
    storageBucket: 'trippy-862df.firebasestorage.app',
    androidClientId: '127365705665-oih1ll3fahj3t2bd280lti31vhut718i.apps.googleusercontent.com',
    iosClientId: '127365705665-99iij3rh6evu4tqoh16sbcioo3meq7l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.trippy.trippy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjW0orJbltG_RpqEkZPA3jl_pw9ONQhYw',
    appId: '1:127365705665:ios:170f882a00b289da440940',
    messagingSenderId: '127365705665',
    projectId: 'trippy-862df',
    storageBucket: 'trippy-862df.firebasestorage.app',
    androidClientId: '127365705665-oih1ll3fahj3t2bd280lti31vhut718i.apps.googleusercontent.com',
    iosClientId: '127365705665-99iij3rh6evu4tqoh16sbcioo3meq7l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.trippy.trippy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASgWTcAHvywXNu0njR0QutsiQJDBpHEB8',
    appId: '1:127365705665:web:39ffc93e9d9b3c2b440940',
    messagingSenderId: '127365705665',
    projectId: 'trippy-862df',
    authDomain: 'trippy-862df.firebaseapp.com',
    storageBucket: 'trippy-862df.firebasestorage.app',
    measurementId: 'G-JTJ8X1PQ2W',
  );
}
